name: Bug Report
description: File a bug report
title: '[Bug]: '
labels: 'type: bug 🐛'
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        # Thanks for taking the time to fill out this bug report!
        ## Preflight Checklist
  - type: checkboxes
    id: preflight-checklist
    attributes:
      label: Preflight Checklist
      options:
        - label: I have read the [Contributing Guidelines](https://github.com/angular-static-server/angular-static-server/blob/master/CONTRIBUTING.md) for this project.
          required: true
        - label: I agree to follow the [Code of Conduct](https://github.com/angular-static-server/angular-static-server/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
          required: true
        - label: I have searched the [issue tracker](https://github.com/angular-static-server/angular-static-server/issues) for an issue that matches the one I want to file, without success.
          required: true
  - type: markdown
    attributes:
      value: |
        ## General Information
  - type: dropdown
    id: bug-type
    attributes:
      label: Bug type
      options:
        - 'Functionality'
        - 'Performance'
        - 'Security vulnerability'
        - 'Other'
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Which version of angular-static-server are you using
      description: e.g. 16.0
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: markdown
    attributes:
      value: |
        ## Detailed description
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: |
        Describe in detail the issue you are having.
        What did you expect to happen? What happened instead? What would you like to see changed?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce the issue
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: |
        1. Step one
        2. Step two
        3. ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell