name: Feature request or enhancement
description: Request for a new component or enhancement of a component
title: "[Feature request]: "
labels: ['type: enhancement']
assignees:
  - octocat
body:
  - type: checkboxes
    id: preflight-checklist
    attributes:
      label: Preflight Checklist
      options:
        - label: I have read the [Contributing Guidelines](https://github.com/angular-static-server/angular-static-server/blob/master/CONTRIBUTING.md) for this project.
          required: true
        - label: I agree to follow the [Code of Conduct](https://github.com/angular-static-server/angular-static-server/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
          required: true
        - label: I have searched the [issue tracker](https://github.com/angular-static-server/angular-static-server/issues) for an issue that matches the one I want to file, without success.
          required: true
  - type: textarea
    id: request
    attributes:
      label: Functionality
      description: What functionality is missing? What would you like to have? Please describe your idea in as much detail as possible.
    validations:
      required: true