# Should be copied into ./Dockerfile via test/create-nginx-container.sh

COPY test/nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --chmod=777 test/angular/dist/i18n /usr/share/nginx/html
RUN rm /usr/share/nginx/html/index.html && \
  apk add brotli && \
  for f in $(find /usr/share/nginx/html/ -name '*.html' -or -name '*.txt' -or -name '*.js' -or -name '*.css'); do gzip -9k $f && brotli -Z $f; done && \
  sed -i 's#events {#load_module modules/ngx_http_brotli_static_module.so;\n\nevents {#g' /etc/nginx/nginx.conf
  #echo "load_module modules/ngx_http_brotli_static_module.so;" >> /etc/nginx/nginx.conf
  #gzip -9k /usr/share/nginx/html/**/*{.html,.txt,.js,.css} && \
  #brotli -Z /usr/share/nginx/html/**/*{.html,.txt,.js,.css}
