name: Continuous Integration
on: [push, pull_request]

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_REPO: ghcr.io/${{ github.repository_owner }}/server-test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: Restore cached Angular Test App
        id: angular-app-cache
        uses: actions/cache@v3
        with:
          path: test/angular/dist
          key: angular-apps-${{ hashFiles('**/test/angular/angular.json', '**/test/angular/package-lock.json', '**/test/angular/projects/**') }}
      - uses: actions/setup-node@v3
        if: steps.angular-app-cache.outputs.cache-hit != 'true'
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'test/angular/package-lock.json'
      - name: Install Angular Test App
        if: steps.angular-app-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile --non-interactive
        working-directory: ./test/angular
      - name: Lint
        run: gofmt -l .
      - name: Build
        run: go build
      - name: Test
        run: go test ./... -coverprofile=coverage.out
      - name: Coverage
        run: go tool cover -func=coverage.out
        
      - name: Login to ghcr.io
        if: github.repository.fork == false
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io --username ${{ github.actor }} --password-stdin
      - name: Container
        run: docker build --tag $IMAGE_REPO:${{ github.ref_name }} .
        env:
          DOCKER_BUILDKIT: 1
      - name: 'Container: Publish image'
        if: github.repository.fork == false
        run: docker push $IMAGE_REPO:${{ github.ref_name }}